name: FastTravel-1.0
main: com.fasttravel.FastTravel
version: 1.0
commands:
  ft:
    description: Teleports you to the specified and discovered place
    usage: /ft <FT-Location>
  create_location:
    description: Create a dicoverable area
    usage: /create_location <name>
      
    