name: FastTravel-0.2
main: com.fasttravel.FastTravel
version: 0.2
commands:
  ft:
    description: Teleports you to the specified and discovered place
    usage: /ft <FT-Location>
  ft_loc:
    description: Create a dicoverable area
    usage: /ft_loc {add|delete} <name>