name: FastTravel-1.0
main: com.fasttravel.FastTravel
version: 1.0
commands:
  ft:
    description: Teleports you to the specified and discovered place
    usage: /ft <FT-Location>
  create_location:
    description: Create a dicoverable area
    usage: /create_location <name> [<x1> <y1> <z1> <x2> <y2> <z2>][2x /sb for the borders]
  specify_ft_point:
    discription: Creates a point where a fast-traveller gets to
    usage: /specify_ft_point
  remove_location:
    discription: Creates a point where a fast-traveller gets to
    usage: /remove_location <name>